This is a fork of [Django-facebook](https://github.com/tschellenbach/Django-facebook) sdk customized for use on [MyWanderlust](https://mywanderlust.in)

This repo has customized integration for our use case so will likely break for you.

Check the original fork if you're looking for integrating the sdk.

Check out https://mywanderlust.in if you're a travel enthusiast!